/*
 * DMA_Driver_Cfg.c
 *
 *  Created on: Jan 4, 2019
 *      Author: zsole
 */

#include "DMA_Driver_Cfg.h"

DMA_Driver_Setup_Type DMA_CONF_SETUP[DMA_DRIVER_CHANNEL_INSTANCE_NUM]=
{
	{
			DMA1_DRIVER_CHANNEL_1,
			DMA_DRIVER_NORMAL_MODE,
			DMA_DRIVER_MEMMORY_TO_MEMMORY_ENABLE,
			DMA_DRIVER_CHANNEL_PRIORITY_MEDIUM,
			DMA_DRIVER_MEMMORY_SIZE_32_BITS,
			DMA_DRIVER_PERIPHERAL_SIZE_8_BITS,
			DMA_DRIVER_MEMMORY_INCREMENT_ENABLE,
			DMA_DRIVER_PERIPHERAL_INCREMENT_ENABLE,
			DMA_DRIVER_DIRECTION_FROM_PERIPHERAL,
			0x05
	}
};

DMA_Driver_Setup_Type* DMA_SETUP = DMA_CONF_SETUP;
