/*
 * SYSTEM_Driver_Cfg.h
 *
 *  Created on: Oct 1, 2018
 *      Author: zsolt.balo
 */

#ifndef DRIVERS_SYSTEM_DRIVER_SYSTEM_DRIVER_CFG_H_
#define DRIVERS_SYSTEM_DRIVER_SYSTEM_DRIVER_CFG_H_

#include "SYSTEM_Driver.h"

#define SYSTEM_DRIVER_CLK_SOURCE 			SYSTEM_DRIVER_SWITCH_TO_PLL
#define SYSTEM_DRIVER_PLL_SOURCE 			SYSTEM_DRIVER_PLL_CLOCK_SRC_HSE
#define SYSTEM_DRIVER_PLL_MULTIPLIER 		SYSTEM_DRIVER_PLLMUL_9
#define SYSTEM_DRIVER_HCLK_DIV 	 			SYSTEM_DRIVER_AHB_NDIV
#define SYSTEM_DRIVER_PCLK1_DIV 			SYSTEM_DRIVER_APB1_DIV2
#define SYSTEM_DRIVER_PCLK2_DIV 			SYSTEM_DRIVER_APB2_NDIV
#define SYSTEM_DRIVER_SLEEP_ENABLE 			NOK
#define SYSTEM_DRIVER_SLEEP_WAKEUP 			SYSTEM_DRIVER_INTERRUPT
#define SYSTEM_DRIVER_SLEEP_MODE 			SYSTEM_DRIVER_SLEEP_ON_EXIT
#define SYSTEM_DRIVER_STOP_ENABLE 			NOK
#define SYSTEM_DRIVER_STOP_WAKEUP 			SYSTEM_DRIVER_INTERRUPT
#define SYSTEM_DRIVER_STANDBY_ENABLE 		NOK
#define SYSTEM_DRIVER_STANDBY_WAKEUP 		SYSTEM_DRIVER_INTERRUPT
#define SYSTEM_DRIVER_LP_DEEPSLEEP 			NOK
#define SYSTEM_DRIVER_USE_WKUP_PIN 			NOK
#define SYSTEM_DRIVER_PVD_ENABLE 			NOK
#define SYSTEM_DRIVER_PVD_THRESHOLD 		SYSTEM_DRIVER_PVD_LEVEL_6

#endif /* DRIVERS_SYSTEM_DRIVER_SYSTEM_DRIVER_CFG_H_ */
